HTTP_TRAFFIC,TCP,*,*,*,80,FORWARD_WORKER_0
HTTPS_TRAFFIC,TCP,*,*,*,443,FORWARD_WORKER_1
DNS_TRAFFIC,UDP,*,*,*,53,FORWARD_WORKER_2
GTPU_TRAFFIC,UDP,*,*,*,2152,FORWARD_WORKER_3
SSH_BLOCK,TCP,*,*,*,22,DROP
DEFAULT,*,*,*,*,*,DROP
